### ISSUE TITLE
Incompatibility with Dual Riders - Mixin Conflict

### ISSUE THREAD

**Issue by AsyncBanana** [apace100/origins-classes#64]
When trying to run 1.19 with Origins Classes, I get an error that causes crashing upon startup:
```
[22/06/2022 16:51:28 PM] [main/ERROR] Mixin apply for mod origins-classes failed origins-classes.mixins.json:ChildCreationMixin$HorseKids from mod origins-classes -> net.minecraft.class_1498: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Conflicting opcodes ALOAD and ALOAD at offset 0 in synthetic bridge method method_5642()Lnet/minecraft/class_1297;
[22/06/2022 16:51:28 PM] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463)
[22/06/2022 16:51:28 PM] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[22/06/2022 16:51:28 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[22/06/2022 16:51:28 PM] Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1498 failed
[22/06/2022 16:51:28 PM] 	at net.minecraft.class_1299.<clinit>(class_1299.java:208)
[22/06/2022 16:51:28 PM] 	at net.minecraft.class_3103.<clinit>(class_3103.java:28)
[22/06/2022 16:51:28 PM] 	at net.minecraft.class_3031.<clinit>(class_3031.java:84)
[22/06/2022 16:51:28 PM] 	at net.minecraft.class_6800.<clinit>(class_6800.java:20)
[22/06/2022 16:51:28 PM] 	at net.minecraft.class_6803.method_39702(class_6803.java:24)
[22/06/2022 16:51:28 PM] 	at net.minecraft.class_5458.method_44104(class_5458.java:98)
[22/06/2022 16:51:28 PM] 	at net.minecraft.class_5458.method_30566(class_5458.java:105)
[22/06/2022 16:51:28 PM] 	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
[22/06/2022 16:51:28 PM] 	at net.minecraft.class_5458.<clinit>(class_5458.java:104)
[22/06/2022 16:51:28 PM] 	at net.minecraft.class_2378.<clinit>(class_2378.java:326)
[22/06/2022 16:51:28 PM] 	at net.minecraft.class_2966.method_12851(class_2966.java:50)
[22/06/2022 16:51:28 PM] 	at net.minecraft.client.main.Main.main(Main.java:154)
[22/06/2022 16:51:28 PM] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
[22/06/2022 16:51:28 PM] 	... 2 more
[22/06/2022 16:51:28 PM] Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1498 failed
[22/06/2022 16:51:28 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419)
[22/06/2022 16:51:28 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
[22/06/2022 16:51:28 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
[22/06/2022 16:51:28 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
[22/06/2022 16:51:28 PM] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[22/06/2022 16:51:28 PM] 	... 15 more
[22/06/2022 16:51:28 PM] Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[22/06/2022 16:51:28 PM] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
[22/06/2022 16:51:28 PM] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
[22/06/2022 16:51:28 PM] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
[22/06/2022 16:51:28 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414)
[22/06/2022 16:51:28 PM] 	... 19 more
[22/06/2022 16:51:28 PM] Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [origins-classes.mixins.json:ChildCreationMixin$HorseKids from mod origins-classes] from phase [DEFAULT] in config [origins-classes.mixins.json] FAILED during APPLY
[22/06/2022 16:51:28 PM] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
[22/06/2022 16:51:28 PM] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
[22/06/2022 16:51:28 PM] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
[22/06/2022 16:51:28 PM] 	... 22 more
[22/06/2022 16:51:28 PM] Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Conflicting opcodes ALOAD and ALOAD at offset 0 in synthetic bridge method method_5642()Lnet/minecraft/class_1297;
[22/06/2022 16:51:28 PM] 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachUniqueMethod(MixinPreProcessorStandard.java:564)
[22/06/2022 16:51:28 PM] 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:351)
[22/06/2022 16:51:28 PM] 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:299)
[22/06/2022 16:51:28 PM] 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277)
[22/06/2022 16:51:28 PM] 	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289)
[22/06/2022 16:51:28 PM] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292)
[22/06/2022 16:51:28 PM] 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
[22/06/2022 16:51:28 PM] 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
[22/06/2022 16:51:28 PM] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[22/06/2022 16:51:28 PM] 	... 22 more
[22/06/2022 16:51:28 PM] [main/ERROR] Minecraft has crashed!
[22/06/2022 16:51:28 PM] Oh no. Minecraft crashed. Please check the logs for any errors and provide these logs when asking for support.
```
Mod list:
```
[22/06/2022 17:03:37 PM] 	- additionalentityattributes 1.0.0+1.19 via apoli
[22/06/2022 17:03:37 PM] 	- additionalstructures 4.0.0
[22/06/2022 17:03:37 PM] 	- amecsapi 1.3.6+mc22w17a via backslot
[22/06/2022 17:03:37 PM] 	- apoli 2.5.0 via origins
[22/06/2022 17:03:37 PM] 	- appleskin 2.4.0+mc1.19
[22/06/2022 17:03:37 PM] 	- architectury 5.7.27
[22/06/2022 17:03:37 PM] 	- backslot 1.2.8
[22/06/2022 17:03:37 PM] 	- badpackets 0.1.2
[22/06/2022 17:03:37 PM] 	- bclib 2.0.5
[22/06/2022 17:03:37 PM] 	- betterend 2.0.2
[22/06/2022 17:03:37 PM] 	- byg 2.0.0.4
[22/06/2022 17:03:37 PM] 	- calio 1.7.0 via apoli
[22/06/2022 17:03:37 PM] 	- cardinal-components 5.0.0-beta.1
[22/06/2022 17:03:37 PM] 	- cardinal-components-base 5.0.0-beta.1 via cardinal-components
[22/06/2022 17:03:37 PM] 	- cardinal-components-block 5.0.0-beta.1 via cardinal-components
[22/06/2022 17:03:37 PM] 	- cardinal-components-chunk 5.0.0-beta.1 via cardinal-components
[22/06/2022 17:03:37 PM] 	- cardinal-components-entity 5.0.0-beta.1 via cardinal-components
[22/06/2022 17:03:37 PM] 	- cardinal-components-item 5.0.0-beta.1 via cardinal-components
[22/06/2022 17:03:37 PM] 	- cardinal-components-level 5.0.0-beta.1 via cardinal-components
[22/06/2022 17:03:37 PM] 	- cardinal-components-scoreboard 5.0.0-beta.1 via cardinal-components
[22/06/2022 17:03:37 PM] 	- cardinal-components-world 5.0.0-beta.1 via cardinal-components
[22/06/2022 17:03:37 PM] 	- charm 4.1.2
[22/06/2022 17:03:37 PM] 	- cloth-basic-math 0.6.1 via cloth-config
[22/06/2022 17:03:37 PM] 	- cloth-config 7.0.72
[22/06/2022 17:03:37 PM] 	- clumps 9.0.0+3
[22/06/2022 17:03:37 PM] 	- com_electronwill_night-config_core 3.6.5 via globaldataandresourcepacks
[22/06/2022 17:03:37 PM] 	- com_electronwill_night-config_toml 3.6.5 via globaldataandresourcepacks
[22/06/2022 17:03:37 PM] 	- com_eliotlash_mclib_mclib 18 via geckolib3
[22/06/2022 17:03:37 PM] 	- com_eliotlash_molang_molang 18 via geckolib3
[22/06/2022 17:03:37 PM] 	- com_github_luben_zstd-jni 1.5.2-2 via dashloader
[22/06/2022 17:03:37 PM] 	- com_moandjiezana_toml_toml4j 0.7.2 via charm
[22/06/2022 17:03:37 PM] 	- controlling 10.0+1
[22/06/2022 17:03:37 PM] 	- creativecore 2.7.2
[22/06/2022 17:03:37 PM] 	- dashloader 4.0.0+1.19
[22/06/2022 17:03:37 PM] 	- dev_quantumfusion_hyphen 0.2.2 via dashloader
[22/06/2022 17:03:37 PM] 	- dev_quantumfusion_taski 1.1.0 via dashloader
[22/06/2022 17:03:37 PM] 	- disable_custom_worlds_advice 3.0
[22/06/2022 17:03:37 PM] 	- dual_riders 1.1.1
[22/06/2022 17:03:37 PM] 	- dualwielding 1.1.2
[22/06/2022 17:03:37 PM] 	- duckling 2.0.2
[22/06/2022 17:03:37 PM] 	- fabric 0.56.1+1.19
[22/06/2022 17:03:37 PM] 	- fabric-api-base 0.4.9+e62f51a3a9 via fabric
[22/06/2022 17:03:37 PM] 	- fabric-api-lookup-api-v1 1.6.7+9ff28f40a9 via fabric
[22/06/2022 17:03:37 PM] 	- fabric-biome-api-v1 9.0.14+b2a4a624a9 via fabric
[22/06/2022 17:03:37 PM] 	- fabric-blockrenderlayer-v1 1.1.18+9ff28f40a9 via fabric
[22/06/2022 17:03:37 PM] 	- fabric-command-api-v1 1.2.6+f71b366fa9 via fabric
[22/06/2022 17:03:37 PM] 	- fabric-command-api-v2 2.1.2+0d55f585a9 via fabric
[22/06/2022 17:03:37 PM] 	- fabric-commands-v0 0.2.23+df3654b3a9 via fabric
[22/06/2022 17:03:37 PM] 	- fabric-containers-v0 0.1.27+df3654b3a9 via fabric
[22/06/2022 17:03:37 PM] 	- fabric-content-registries-v0 3.1.1+82552130a9 via fabric
[22/06/2022 17:03:37 PM] 	- fabric-convention-tags-v1 1.0.8+37622d24a9 via fabric
[22/06/2022 17:03:37 PM] 	- fabric-crash-report-info-v1 0.2.3+bd0a0d4aa9 via fabric
[22/06/2022 17:03:37 PM] 	- fabric-data-generation-api-v1 5.1.0+a680b9b4a9 via fabric
[22/06/2022 17:03:37 PM] 	- fabric-dimensions-v1 2.1.27+72da3b3da9 via fabric
[22/06/2022 17:03:37 PM] 	- fabric-entity-events-v1 1.4.16+9ff28f40a9 via fabric
[22/06/2022 17:03:37 PM] 	- fabric-events-interaction-v0 0.4.26+9ff28f40a9 via fabric
[22/06/2022 17:03:37 PM] 	- fabric-events-lifecycle-v0 0.2.25+df3654b3a9 via fabric
[22/06/2022 17:03:37 PM] 	- fabric-game-rule-api-v1 1.0.19+18990361a9 via fabric
[22/06/2022 17:03:37 PM] 	- fabric-item-api-v1 1.5.4+767db26ea9 via fabric
[22/06/2022 17:03:37 PM] 	- fabric-item-groups-v0 0.3.24+9ff28f40a9 via fabric
[22/06/2022 17:03:37 PM] 	- fabric-key-binding-api-v1 1.0.18+9ff28f40a9 via fabric
[22/06/2022 17:03:37 PM] 	- fabric-keybindings-v0 0.2.16+df3654b3a9 via fabric
[22/06/2022 17:03:37 PM] 	- fabric-lifecycle-events-v1 2.1.0+33fbc738a9 via fabric
[22/06/2022 17:03:37 PM] 	- fabric-loot-api-v2 1.0.2+9e7660c6a9 via fabric
[22/06/2022 17:03:37 PM] 	- fabric-loot-tables-v1 1.1.2+9e7660c6a9 via fabric
[22/06/2022 17:03:37 PM] 	- fabric-message-api-v1 1.0.1+513f4a59a9 via fabric
[22/06/2022 17:03:37 PM] 	- fabric-mining-level-api-v1 2.1.9+33fbc738a9 via fabric
[22/06/2022 17:03:37 PM] 	- fabric-models-v0 0.3.15+9ff28f40a9 via fabric
[22/06/2022 17:03:37 PM] 	- fabric-networking-api-v1 1.0.27+7fe97409a9 via fabric
[22/06/2022 17:03:37 PM] 	- fabric-networking-v0 0.3.14+df3654b3a9 via fabric
[22/06/2022 17:03:37 PM] 	- fabric-object-builder-api-v1 4.0.6+9ff28f40a9 via fabric
[22/06/2022 17:03:37 PM] 	- fabric-particles-v1 1.0.8+dc39553aa9 via fabric
[22/06/2022 17:03:37 PM] 	- fabric-permissions-api-v0 0.1-SNAPSHOT via spark
[22/06/2022 17:03:37 PM] 	- fabric-registry-sync-v0 0.9.16+92cf9a3ea9 via fabric
[22/06/2022 17:03:37 PM] 	- fabric-renderer-api-v1 1.0.8+9ff28f40a9 via fabric
[22/06/2022 17:03:37 PM] 	- fabric-renderer-indigo 0.6.7+c57dbccaa9 via fabric
[22/06/2022 17:03:37 PM] 	- fabric-renderer-registries-v1 3.2.18+df3654b3a9 via fabric
[22/06/2022 17:03:37 PM] 	- fabric-rendering-data-attachment-v1 0.3.12+9ff28f40a9 via fabric
[22/06/2022 17:03:37 PM] 	- fabric-rendering-fluids-v1 3.0.5+9ff28f40a9 via fabric
[22/06/2022 17:03:37 PM] 	- fabric-rendering-v0 1.1.20+df3654b3a9 via fabric
[22/06/2022 17:03:37 PM] 	- fabric-rendering-v1 1.10.14+9ff28f40a9 via fabric
[22/06/2022 17:03:37 PM] 	- fabric-resource-conditions-api-v1 2.0.9+e62f51a3a9 via fabric
[22/06/2022 17:03:37 PM] 	- fabric-resource-loader-v0 0.5.4+db8596f1a9 via flytre_lib
[22/06/2022 17:03:37 PM] 	- fabric-screen-api-v1 1.0.23+9ff28f40a9 via fabric
[22/06/2022 17:03:37 PM] 	- fabric-screen-handler-api-v1 1.2.6+9ff28f40a9 via fabric
[22/06/2022 17:03:37 PM] 	- fabric-textures-v0 1.0.18+9ff28f40a9 via fabric
[22/06/2022 17:03:37 PM] 	- fabric-transfer-api-v1 2.0.9+e62f51a3a9 via fabric
[22/06/2022 17:03:37 PM] 	- fabric-transitive-access-wideners-v1 1.1.1+9e7660c6a9 via fabric
[22/06/2022 17:03:37 PM] 	- fabricloader 0.14.8
[22/06/2022 17:03:37 PM] 	- flytre_lib 1.8.4
[22/06/2022 17:03:37 PM] 	- fwaystones 3.0.1+mc1.19
[22/06/2022 17:03:37 PM] 	- geckolib3 3.1.3
[22/06/2022 17:03:37 PM] 	- globaldataandresourcepacks 1.13_fabric
[22/06/2022 17:03:37 PM] 	- graveyard 1.10
[22/06/2022 17:03:37 PM] 	- graveyard_biomes 1.2
[22/06/2022 17:03:37 PM] 	- guardvillagers 1.19-1.0.14
[22/06/2022 17:03:37 PM] 	- herdspanic 1.0.6
[22/06/2022 17:03:37 PM] 	- indium 1.0.6+mc1.19
[22/06/2022 17:03:37 PM] 	- inventoryhud 3.4.2
[22/06/2022 17:03:37 PM] 	- itemphysiclite 1.5.0
[22/06/2022 17:03:37 PM] 	- java 17
[22/06/2022 17:03:37 PM] 	- lithium 0.8.0
[22/06/2022 17:03:37 PM] 	- midnightlib 0.5.2 via repurposed_structures
[22/06/2022 17:03:37 PM] 	- minecraft 1.19
[22/06/2022 17:03:37 PM] 	- moborigins 1.9.0
[22/06/2022 17:03:37 PM] 	- modmenu 4.0.0
[22/06/2022 17:03:37 PM] 	- morebannerfeatures 1.1.3
[22/06/2022 17:03:37 PM] 	- morevillagers 4.0.1
[22/06/2022 17:03:37 PM] 	- omega-config 1.2.2-1.18.1 via graveyard_biomes
[22/06/2022 17:03:37 PM] 	- org_joml_joml 1.10.4 via sodium
[22/06/2022 17:03:37 PM] 	- origins 1.6.1
[22/06/2022 17:03:37 PM] 	- phosphor 0.8.1
[22/06/2022 17:03:37 PM] 	- playerabilitylib 1.6.0 via apoli
[22/06/2022 17:03:37 PM] 	- reach-entity-attributes 2.3.0-SNAPSHOT via origins
[22/06/2022 17:03:37 PM] 	- repurposed_structures 6.0.4+1.19
[22/06/2022 17:03:37 PM] 	- roughlyenoughitems 9.0.491
[22/06/2022 17:03:37 PM] 	- sodium 0.4.2+build.16
[22/06/2022 17:03:37 PM] 	- spark 1.9.13
[22/06/2022 17:03:37 PM] 	- stoneholm 1.4.4
[22/06/2022 17:03:37 PM] 	- talkbubbles 1.0.2
[22/06/2022 17:03:37 PM] 	- terrablender 2.0.0.113
[22/06/2022 17:03:37 PM] 	- villager-hats 1.4.1
[22/06/2022 17:03:37 PM] 	- villagernames 4.0.4
[22/06/2022 17:03:37 PM] 	- wthit 5.4.3
[22/06/2022 17:03:37 PM] 	- xaerominimap 22.9.3
```
Version: 1.19

**Comment by AsyncBanana** [comment]
As it turns out, this is caused by a mixin conflict with Dual Riders
